---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: promotion
  namespace: podinfo
spec:
  type: generic
  address: "https://sa-demo.trial.cx.weave.works/promotion/default/podinfo-app/north-america"
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: promotion
  namespace: podinfo
spec:
  eventSeverity: info
  eventSources:
  - kind: HelmRelease
    name: podinfo
  inclusionList:
  - .*test.*succeeded
  providerRef:
    name: promotion