---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: promotion
  namespace: fabrikam-app
spec:
  type: generic
  address: "https://promotions.demo3.weavegitops.com/promotion/default/podinfo/north-america"
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: promotion
  namespace: fabrikam-app
spec:
  eventSeverity: info
  eventSources:
  - kind: HelmRelease
    name: fabrikam-app
  exclusionList:
  - .*upgrade.*has.*started
  - .*is.*not.*ready
  - ^Dependencies.*
  providerRef:
    name: promotion