name: weave-policy checks
on:
  pull_request:
    branches:
      - main 

jobs:
  weave-policy-checks:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Policy Scan Helm Chart
        uses: weaveworks/weave-action@v1
        with:
          path: charts/podinfo/
          helm-values-file: charts/podinfo/values.yaml
          policies-path: policies
          remediate: true
          sarif-file: helm-results.sarif

      - uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: helm-results.sarif
