apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
  annotations:
    metadata.weave.works/app-url: http://${CLUSTER_NAME}-default.sa-demo.trial.cx.weave.works/
spec:
  interval: 2m
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: podinfo-helm-repo
      version: x.x.x # {"$promotion": "default:podinfo-app:dev"}
  targetNamespace: podinfo
  test:
    enable: true
    timeout: 5m
    ignoreFailures: false
  install:
    remediation:
      retries: 2
  upgrade:
    remediation:
      retries: 2
  rollback:
    timeout: 5m
    disableWait: false
    disableHooks: false
    recreate: false
    force: false
    cleanupOnFail: false
  values:
    service:
      enabled: false
      externalPort: 80
    ingress:
      enabled: false
    replicaCount: 1
    ui:
      message: "Hi, this message is from the Helm values for dev"
      color: ""
    canary:
      enabled: false
      loadtester:
        url: "flagger-loadtester.istio-system:80"
      ingress:
        url: "istio-gateway.istio-system:80"
    hpa:
      enabled: false
      maxReplicas: 1
