---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: promotion
  namespace: podinfo
spec:
  type: generic
  address: "https://sa-demo.trial.cx.weave.works/promotion/default/podinfo-app/dev"
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: promotion
  namespace: podinfo
spec:
  eventSeverity: info
  eventSources:
  - kind: HelmRelease
    name: podinfo
  exclusionList:
    - .*error.*
    - .*failed.*
    - .*install.*succeeded
    - .*upgrade.*succeeded
    - .*rollback.*succeeded
    - .*install.*has.*started
    - .*upgrade.*has.*started
    - .*is.*not.*ready
    - ^Dependencies.*
  providerRef:
    name: promotion