apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: "gitrepository"
  namespace: podinfo
spec:
  interval: 30s
  url: "https://github.com/weavegitops/application-promotion-podinfo2"
  ref:
    branch: "${BRANCH:=main}"